---
title: "My name is Hugo (Xiaohu) Wang!"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Education

**Columbia University, Mailman School of Public Health**

New York, NY

MPH, Health Policy & Management, Applied Biostatistics | GPA: 4.0

9/2020-5/2022


**New York University, College of Art and Science**

New York, NY

BS, Biology, Minor in Studio Art | GPA: 3.5 | GRE: 331

9/2016-5/2020

## Professional Experiences


### SOMOS Community Care                                                                                                                                        
New York, NY

Summer Strategy Analyst  

5/2021-Present

*	Planned and implemented Social Determinants of Health intervention program, funded by the State Medicaid Redesign Team, to support SOMOS’ value-based payment level 3 contract (only one in NYS). 

* Collaborated with: 

         -	3 community-based organizations to roll out the program. Composed program manual for CBO partners.

         -	Clinical Data team to build a centralized system for patient data tracking & reporting. Administered data collection and entering.

         -	Care Management team to formulate patient engagement strategies and organize performance management meetings to assess and evaluate the program. 

* Analyzed patient data to develop reports of the project plan and progress to Managed Care Organization partners and NYSDOH. 


### International Healthcare Leadership/JuniperMD	

New York, NY

Fellowship	 

9/2020-5/2021

* Prepared pitch deck for C-Suites to present JuniperMD’s enterprise wellness offering to investors: Synthesized data of business portfolio, service provisions, enterprise wellness market size and growth drivers, competitive landscape, and the implementation of enterprise onsite clinics in the US and China markets.

* Kicked off a new business project for a probiotics product to enter China market: 
       -	Collaborated with a team of 6 including US-based investors and China-based clients
       
       -	Led the market research on manufacturers info (Merck, Roche, etc.), market entry regulations, target customers (demographics, preferences, unmet needs), and developed a marketing proposal 
       
* Managed JuniperMD’s LinkedIn page including content development, outreach, page maintenance and postings. Boosted followers by 60% and post impressions by 700%.


### ASIA SOCIETY/YOUNG GREEN TECH (YGT)	

New York, NY

Project Leader    

1/2020-9/2020

*	Recruited 200+ event participants from new energy & tech start-ups within 1 month. Processed participants data in Excel (pivot tables, charts) and weekly presented recruiting status in 10 local countries.

* Spearheaded YGT Alumni Project and improved communication of YGT alumni by creating and maintaining group chats across platforms (WeChat, WhatsApp, & Facebook).


### NORTHBOUND.IS	

Reykjavik, Iceland

Marketing Consultant  

1/2019-5/2020

*	Served as a consultant and translator for the CEO on Search Engine Optimization and content strategy.

*	Expanded customer base in the East Asian market by 60% within a year for the company. 



### International Center for AIDS Prevention

New York, NY

Graduate Research Fellowship    

9/2021-Present

* Supported research publications based on survey data obtained from alumni.

*	Reviewed and analyzed alumni survey results to develop ongoing engagement strategies for targeted alumni segments.


## Leadership

### Columbia Mailman Consulting Club

New York, NY

President of External Affair     

10/2020-Present                


### A Little Bit Human (Subsidiary of New Saga Media)

New York, NY  

Co-founder, Healthcare Content Manager, Initiative Director	

11/2020-Present

*	Establish collaboration with charity groups to raise awareness and social issues and funds for activism. 


## Courses & Skills

*	**Courses**: Molecular Biology, Organic Chemistry, Microbiology, Healthcare Accounting & Budgeting, Biostatistics, Epidemiology, Health Policy & Political Analysis, Regression, Data Science, etc. 

*	**Skills**: Microsoft Word, Excel, PowerPoint, R, STATA, SAS, Adobe Photoshop, Adobe Illustrator, Graphic Design
